version: "3.7" ## whut
services: 
  fluentbit:
    build: fluent-bit/
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  nginx:
    build: nginx/
    depends_on:
      - fluentbit
      - authenticate
    logging:
      driver: fluentd
      options:
        tag: nginx
    networks: 
      - frontnet
    ports: 
      - 80:80

  authenticate:
    build: authenticate/
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        tag: authenticate
    networks: 
      - frontnet
    expose: 
      - 8080

networks:
  frontnet: